variableGroups:
  - title: "Networking"
    visible: true
    variables:
      -region
      -ad_number
      -subnet_cidr_block_list
      -fault_domains

  - title: "Credentials"
    visible: true
    variables:
      -tenancy_ocid
      -compartment_ocid
      -config_file_profile

  - title: "VLZ"
    visible: true
    variables:
      -vlz_refresh_token
      -vlz_s3_path_to_conn
      -vlz_rest_apigw

  - title: "Media"
    visible: true
    variables:
      -media_image_id
      -media_num_of_instances
      -media_shape
      -media_num_of_ocpus
      -media_memory_in_gbs
      -media_use_placement_group
      -media_ignore_cpu_mem_req

  - title: "App"
    visible: true
    variables:
      -app_image_id
      -app_num_of_instances
      -app_shape
      -app_num_of_ocpus
      -app_memory_in_gbs
      -app_use_placement_group
      -app_ignore_cpu_mem_req


