# Title shown in Application Information tab.
title: Volumez on Oracle Cloud Infrastructure
# Sub Title shown in Application Information tab.
description: Deploy Volumez stack on OCI Marketplace.
schemaVersion: 1.1.0
version: "20241013"

# URL of Logo Icon used on Application Information tab. You can copy the contentId from the Marketplace listing logo URL in the Marketplace Partner portal.
# (Optional)
logoUrl: https://partner.cloudmarketplace.oracle.com/partner/content?contentId=174607522

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
source:
  type: marketplace
  reference: 167616210

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
      - subnet_cidr_block_list
      - vlz_s3_path_to_conn
      - vlz_rest_apigw
      - media_image_id
      - media_shape
      - media_memory_in_gbs
      - media_num_of_ocpus
      - media_ignore_cpu_mem_req
      - media_num_of_instances
      - media_use_placement_group
      - app_image_id
      - app_shape
      - app_memory_in_gbs
      - app_num_of_ocpus
      - app_ignore_cpu_mem_req
      - app_num_of_instances
      - app_use_placement_group

  - title: "OCI Configuration"
    visible: true
    variables:
      - tenancy_ocid
      - compartment_ocid

  - title: "Placement"
    variables:
      - ${region}
      - ${availability_domain_name}
      - ad_number
      - fault_domains

  - title: "Login Credentials"
    visible: true
    variables:
      - email
      - password

  - title: "SSH Public Key"
    variables:
      - generate_public_ssh_key
      - public_ssh_key

  # - title: "Virtual Cloud Network"
  #   visible: false
  #   variables:
  #     - subnet_cidr_block_list

  - title: "Volumez"
    visible: false
    variables:
      # - vlz_refresh_token
      - vlz_s3_path_to_conn
      - vlz_rest_apigw

  - title: "Volumez infrastructure Configurations"
    visible: true
    variables:
      - env_size
      - postgres_version

variables:
# Login Credentials
  email:
    type: string
    title: Email
    description: Your email address.
    required: true

  password:
    type: password
    confirmation: true
    title: Password
    description: "The password must be more than 8 characters and include at least one uppercase letter, one lowercase letter, one number, and one of the following special characters: @#%^*_+-:?.,[]{}"
    required: true
    pattern: "^(?=.*[!@#%^*_+\\-:?.,\\[\\]\\{\\}])(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?!.*[$\\(\\)]).{8,32}$"

#SSH Public Key
  generate_public_ssh_key:
    type: boolean
    title: "Auto-generate public ssh key?"
    description: "Auto-generate a public key and assign to the compute instances. Uncheck to provide your own public key or leave blank not to use any attach any key to the compute instance."
    required: false
    default: true

  public_ssh_key:
    type: oci:core:ssh:publicKey
    title: SSH Public Key
    description: Your SSH public key.
    required: false
    visible:
      and:
        - not:
          - generate_public_ssh_key

# OCI Configuration
  tenancy_ocid:
    visible: false
    type: string
    title: Tenancy OCID
    description: The OCID of your tenancy.
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Compartment OCID
    description: The OCID of the compartment to deploy resources into.
    required: true

  # Region and Availability
  # region:
  #   visible: false
  #   type: oci:identity:region:name
  #   title: Region
  #   description: The OCI region to deploy resources into.
  #   required: true

  availability_domain_name:
    type: oci:identity:availabilitydomain:name	
    dependsOn:
      compartmentId: ${compartment_ocid}
    title: Availability Domain Name
    description: The availability domain to deploy instances in.
    required: true
    default: 1

  ad_number:
    visible: false
    type: number
    title: Availability Domain Number
    description: The number of availability domains to deploy instances in.
    required: true
    default: 1

  fault_domains:
    visible: false
    type: list(string)
    title: Fault Domains
    description: A list of fault domains to distribute instances across.
    required: true
    default: ["FAULT-DOMAIN-1, FAULT-DOMAIN-2", "FAULT-DOMAIN-3"]

  # Virtual Cloud Network
  subnet_cidr_block_list:
    type: list(string)
    title: Subnet CIDR Blocks
    description: A list of CIDR blocks for the subnets.
    default: ["10.1.20.0/24"]

  # VLZ
  vlz_s3_path_to_conn:
    type: string
    title: VLZ S3 Path to Connector
    description: The S3 path to the VLZ connector.
    required: true
    default: "https://signup.volumez.com/oci_poc_14/ubuntu"

  vlz_rest_apigw:
    type: string
    title: VLZ REST API Gateway
    description: The URL of the VLZ REST API Gateway.
    required: true
    default: "https://oci.api.volumez.com"

  # Environment Size
  env_size:
    type: enum
    title: VLZ Environment Size
    description: >+
        Small: 25K TPS, 2xVM.Standard.E5.Flex (8 OCPU, 32GB Memory), 2xVM.DenseIO.E5.Flex (8 OCPU)------------------------------------------------------------------------------------Medium: 40K TPS, 2xVM.Standard.E5.Flex (16 OCPU, 32GB Memory), 2xVM.DenseIO.E5.Flex (16 OCPU)------------------------------------------------------------------------------Large: 70K TPS, 2xVM.Standard.E5.Flex (32 OCPU, 32GB Memory), 4xVM.DenseIO.E5.Flex (16 OCPU)---------------------------------------------------------------------------------
    required: true
    enum:
      - Small
      - Medium
      - Large
    default: "Small"

  # Postgres
  postgres_version:
    type: enum
    title: Postgres Version (App VM)
    description: This version of Postgres will be installed on application VM.
    required: true
    enum:
      - 13
      - 14
      - 15
    default: "13"


# Outputs (add your relevant outputs here)
outputGroups:
  - title: VLZ Endpoint
    outputs: 
      - oci_endpoint
      - username
      - password

  - title: Media Nodes
    outputs: 
      - media_instance_pool_name
      - media_instance_pool_id
      - public-ip-media-instances
  
  - title: Application Nodes
    outputs: 
      - app_instance_pool_name
      - app_instance_pool_id
      - public-ip-app-instances

  - title: SSH
    outputs: 
      - tls_private_key


outputs:
  tls_private_key:
    title: Generated SSH private key
    sensitive: true

  media_instance_pool_name:
    title: "Media Instance Pool Name"

  media_instance_pool_id:
    title: "Media Instance Pool ID"

  app_instance_pool_name:
    title: "Application Instance Pool Name"

  app_instance_pool_id:
    title: "Application Instance Pool ID"

  public-ip-app-instances:
    title: "Application Instances Public IP"
    type: map

  public-ip-media-instances:
    title: "Media Instances Public IP"
    type: map

  oci_endpoint:
    title: VLZ-OCI Endpoint
    type: link

  username:
    title: Username

  password:
    title: Password
    sensitive: true


